image: Visual Studio 2015

platform:
    - x64

environment:
  matrix:
    - LISP: sbcl-bin

install:
  - appveyor DownloadFile "https://ci.appveyor.com/api/buildjobs/nrfdm3edqcur4l8a/artifacts/Roswell-x86_64.zip" -FileName Roswell-x86_64.zip
  - 7z x Roswell-x86_64.zip
  - set PATH=%CD%/roswell;%PATH%
  - ros install %LISP%
  - ps: ros run -e '123' -q
  - ps: ros run -e '(print "asdf")' -q
  - ps: ros run -e '(format t "~a ~a~%" (lisp-implementation-type) (lisp-implementation-version))' -q

build: false

test_script:
  # Run a basic sanity test for human-readable output.
  - ps: ros run -e '(ql:quickload :ip-interfaces)' -e '(format t "~a~%" (ip-interfaces:get-ip-interfaces))' -q

  # Run test suite.
  - ps: ros run -e '(ql:quickload :prove)' -e '(ql:quickload :ip-interfaces)' -e '(asdf:test-system :ip-interfaces)' -q
