image: Visual Studio 2015

platform:
    - x64

environment:
  matrix:
    - LISP: sbcl-bin

install:
  - appveyor DownloadFile https://ci.appveyor.com/api/projects/snmsts/roswell-en89n/artifacts/Roswell-x86_64.zip?branch=master&job=Environment%3A%20MSYS2_ARCH%3Dx86_64,%20MSYS2_BITS%3D64,%20MSYSTEM%3DMINGW64,%20METHOD%3Dcross -FileName Roswell-x86_64.zip
  - 7z x Roswell-x86_64.zip
  - dir
